### ISSUE TITLE
Why you don't use the features from the Java standard library?

### ISSUE THREAD

**Issue by Cach30verfl0w** [FlorianMichael/Registry-Conventions#1]
Java has the Consumer class in the standard library. There I ask myself why one programs such an IAddListener or IRemoveListener, which can be realized by simple implementation of the StdLib of Java.
~ Cach30verfl0w

**Comment by FlorianMichael** [comment]
Consumers were only added in Java 8, this convention is intended to be as downwardly compact as possible, except for the example, and also simply serves to improve code structure and comprehensibility.
